import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import products from "../products.json";
export default function Home() {
	// console.log("products", products);
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href='https://nextjs.org'>Next.js!</a>
				</h1>

				<p>deuy</p>
				<div className='flex flex-row gap-4'>
					{products.map((prd) => {
						console.log(prd.title);
						console.log(prd.price);
						return (
							<a href='' key={prd.id}>
								<Image
									src={prd.image}
									className='rounded-xl'
									alt={prd.title}
									width='550'
									height='550'
								/>

								<h2 className='font-bold'>{prd.title}</h2>
								<p className='font-bold text-sm pb-2'>$ {prd.price}</p>
								<p>{prd.description}</p>
							</a>
						);
						// const { tiitle, price, Description, image } = product;
					})}
				</div>
				<div className={styles.grid}>
					{/* <a href='https://nextjs.org/docs' className={styles.card}>
						<Image
							src='./gadgets/gadgets1.jpg'
							className='rounded-xl'
							alt=''
							width='550'
							height='550'
						/>
						<h2 className='font-bold'>111Gadgets</h2>
						<p className='font-bold text-sm pb-2'>$ 150.00</p>
						<p>Find Awesome 2022 Gadgtes</p>
					</a>

					<a href='https://nextjs.org/learn' className={styles.card}>
						<Image
							src='./book/book1.jpg'
							className='rounded-xl h-48 w-32 mx-auto'
							alt=''
						/>
						<h2 className='font-bold'>Books</h2>
						<p className='font-bold text-sm pb-2'>$ 150.00</p>
						<p>Find All Self-Help Books, ever </p>
					</a>

					<a
						href='https://github.com/vercel/next.js/tree/canary/examples'
						className={styles.card}>
						<Image src='./gift/gift1.jpeg' className='rounded-xl' alt='' />
						<h2 className='font-bold'>Gifts</h2>
						<p className='font-bold text-sm pb-2'>$ 150.00</p>
						<p>Find all awesome gifts for your Close Peoples</p>
					</a> */}
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'>
					Powered by{" "}
					<span className={styles.logo}>
						<Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}
